#Train/val/test sets
path: ../datasets/alldumps
train: images/train
val: images/val
test: #test images

#Classes
names:
    0: ACT_NUM
    1: ADDR_TO
    2: ADD_FRT_CHG
    3: ADD_NOT
    4: AGNT_CRR
    5: AGNT_EMAIL
    6: AMT
    7: AMT_CUR
    8: AMT_CUR_WRD
    9: AMT_WRD
    10: AODP
    11: AODT
    12: APPL_ADDR
    13: APPL_COUNTRY
    14: APPL_EMAIL
    15: APPL_NAME
    16: APP_NME_ADD
    17: APP_RULES
    18: ASSR
    19: AWB_NUM
    20: BALE_NUM
    21: BAT_NUM
    22: BA_NUM
    23: BENF_ADDR
    24: BENF_COUNTRY
    25: BENF_NAME
    26: BENF_VAT_NUM
    27: BEN_NME_ADD
    28: BL_DATE
    29: BL_NUM
    30: BL_TITLE
    31: BNK_BIN
    32: BN_CNF_DCL
    33: BN_FAX_NO
    34: BN_STMT
    35: BN_TEL_NUM
    36: CERT_AUTH
    37: CFR_AMT
    38: CHARGES
    39: CLM_AGNT
    40: CLM_PY_AT
    41: CLM_TL_NO
    42: CNTRLR_NM
    43: CNTR_NUM
    44: CNT_DT
    45: CNT_NO
    46: CN_NUM
    47: CO
    48: COL_BNK
    49: COV_REQD
    50: CO_SUP
    51: CRD_INS
    52: CRR
    53: CR_NUM
    54: CSGN
    55: CSGN_NME
    56: CUR
    57: DA_FAX
    58: DA_PNO
    59: DEL_AGNT
    60: DEL_TRM
    61: DOC_LST
    62: DRFT_NO
    63: DRWEE
    64: DRWER
    65: DRWER_ADD
    66: DRWER_SIG
    67: DT
    68: ETA
    69: EXPTR
    70: EXP_DT
    71: FLT_NUM
    72: FM_NUM
    73: FNL_DST
    74: FOB_AMT
    75: FRT
    76: FRT_NOT
    77: FRT_NT1
    78: FX_INST
    79: GOODS
    80: GR_WGT
    81: GR_WGT_NUM
    82: GR_WGT_UNIT
    83: HS_CODE
    84: IC_EMAIL
    85: IC_NMADD
    86: IEC_CODE
    87: INCOTERMS
    88: INS
    89: INSR
    90: INS_NUM
    91: INV_DT
    92: INV_NUM
    93: INV_NUM
    94: IP_DT
    95: IP_NUM
    96: IRC_NO
    97: IREF_NO
    98: ISR
    99: ISR_NME
    100: ISSBANK
    101: ISS_DT
    102: ISS_PL
    103: LCAF_NO
    104: LC_ISS_DT
    105: LC_NUM
    106: LOT_NUM
    107: MANF_NAME_ADD
    108: MAT_DT
    109: MFG_DT
    110: NET_WGT_NUM
    111: NET_WGT_UNIT
    112: NO_ITEMS
    113: NO_ORG_ISS
    114: NO_ROL
    115: NTFY_PRTY
    116: NTFY_PRTY2
    117: NTFY_PRTY_ADD
    118: NTFY_PRTY_NME
    119: NTN_NUM
    120: NT_WGT
    121: NUM_CNT
    122: NUM_PLT
    123: ODR_NUM
    124: ON_BRD_DT
    125: ON_BRD_NOT
    126: ORDER_DT
    127: ORG_NUM
    128: PAYEE
    129: PCK_COND
    130: PCK_DT
    131: PCK_NUM
    132: PIN_NUM
    133: PI_DT
    134: PI_NUM
    135: PLACE_RECEIPT
    136: PL_NUM
    137: PMT_TRMS
    138: PN_APPL
    139: POD
    140: POL
    141: PO_DATE
    142: PO_NO
    143: PR_BNK_NME_ADD
    144: QTY
    145: RECV_NME_ADD
    146: REF_BNK
    147: REMI_BNK
    148: RSV_SOB
    149: SHIP_DT
    150: SHPER
    151: SHPER_ADD
    152: SHPER_NME
    153: SHP_CO
    154: SHP_DT
    155: SHP_LD_CNT_TRM
    156: SHP_MARKS
    157: SIGN
    158: SIGN_CPT
    159: SL_NUM
    160: STMT
    161: SURV
    162: TIN_NUM
    163: TITLE
    164: TNR
    165: TOTAL_AMT
    166: TOT_MSRM
    167: TOT_MSRM_UNT
    168: TOT_PKGS
    169: TOT_QTY
    170: TO_ADDR
    171: TRANS_MODE_CLS
    172: TRM_CON
    173: TR_WGT
    174: TYPE
    175: UNT_PRC
    176: VAT_NUM
    177: VOY
    178: VSL
