#paths
path: ~mlenv_1/datasets/alldumps
train: images/train
val: images/val
test: null

#Classes
names:
  0: CERT_AUTH
  1: TOT_PKGS
  2: NO_ROL
  3: DRWER
  4: INSR
  5: NT_WGT
  6: TOT_QTY
  7: FX_INST
  8: HS_CODE
  9: DT
  10: ADD_NOT
  11: NET_WGT_UNIT
  12: PLACE_RECEIPT
  13: PI_NUM
  14: IRC_NO
  15: LOT_NUM
  16: APP_NME_ADD
  17: ASSR
  18: BENF_NAME
  19: TRANS_MODE_CLS
  20: BEN_NME_ADD
  21: SHIP_DT
  22: INS_NUM
  23: NTFY_PRTY_NME
  24: AODT
  25: ISSBANK
  26: IC_EMAIL
  27: IP_NUM
  28: STMT
  29: CN_NUM
  30: VOY
  31: PIN_NUM
  32: CLM_TL_NO
  33: SURV
  34: PO_DATE
  35: LC_NUM
  36: NTFY_PRTY_ADD
  37: TR_WGT
  38: APPL_NAME
  39: PI_DT
  40: NTN_NUM
  41: AMT
  42: ISS_PL
  43: APPL_ADDR
  44: ADD_FRT_CHG
  45: CNT_DT
  46: BNK_BIN
  47: AWB_NUM
  48: TITLE
  49: LCAF_NO
  50: ODR_NUM
  51: INV_DT
  52: GR_WGT_UNIT
  53: SHPER
  54: VSL
  55: NTFY_PRTY
  56: SHP_CO
  57: EXP_DT
  58: CSGN
  59: FNL_DST
  60: BAT_NUM
  61: EXPTR
  62: APPL_EMAIL
  63: NO_ORG_ISS
  64: POD
  65: TIN_NUM
  66: DEL_TRM
  67: CNTR_NUM
  68: MFG_DT
  69: BENF_VAT_NUM
  70: BL_TITLE
  71: SHPER_ADD
  72: CNTRLR_NM
  73: ISS_DT
  74: AMT_WRD
  75: ACT_NUM
  76: IC_NMADD
  77: FLT_NUM
  78: TYPE
  79: NET_WGT_NUM
  80: ORG_NUM
  81: DA_FAX
  82: CLM_PY_AT
  83: BALE_NUM
  84: CO
  85: FOB_AMT
  86: ISR_NME
  87: CHARGES
  88: BL_DATE
  89: SIGN
  90: COL_BNK
  91: CNT_NO
  92: AGNT_EMAIL
  93: INCOTERMS
  94: FM_NUM
  95: RECV_NME_ADD
  96: RSV_SOB
  97: BN_TEL_NUM
  98: UNT_PRC
  99: INS
  100: CR_NUM
  101: DEL_AGNT
  102: SL_NUM
  103: TOTAL_AMT
  104: DRWEE
  105: PR_BNK_NME_ADD
  106: CO_SUP
  107: AODP
  108: REMI_BNK
  109: ADDR_TO
  110: AMT_CUR_WRD
  111: DRWER_SIG
  112: DRFT_NO
  113: CLM_AGNT
  114: TRM_CON
  115: BA_NUM
  116: TOT_MSRM_UNT
  117: FRT_NOT
  118: APP_RULES
  119: CFR_AMT
  120: BN_STMT
  121: DA_PNO
  122: ON_BRD_NOT
  123: CRR
  124: APPL_COUNTRY
  125: PO_NO
  126: SHP_MARKS
  127: ISR
  128: FRT
  129: LC_ISS_DT
  130: BENF_COUNTRY
  131: SHP_LD_CNT_TRM
  132: AMT_CUR
  133: PL_NUM
  134: SHPER_NME
  135: GR_WGT
  136: COV_REQD
  137: PN_APPL
  138: CRD_INS
  139: SIGN_CPT
  140: CUR
  141: PCK_DT
  142: FRT_NT1
  143: PMT_TRMS
  144: TOT_MSRM
  145: ORDER_DT
  146: MANF_NAME_ADD
  147: PCK_COND
  148: REF_BNK
  149: BL_NUM
  150: NUM_PLT
  151: NUM_CNT
  152: SHP_DT
  153: MAT_DT
  154: INV_NUM
  155: VAT_NUM
  156: POL
  157: GR_WGT_NUM
  158: INV_NUM
  159: NTFY_PRTY2
  160: BN_FAX_NO
  161: IEC_CODE
  162: TNR
  163: ETA
  164: QTY
  165: DOC_LST
  166: PAYEE
  167: IP_DT
  168: BN_CNF_DCL
  169: PCK_NUM
  170: NO_ITEMS
  171: DRWER_ADD
  172: TO_ADDR
  173: GOODS
  174: IREF_NO
  175: CSGN_NME
  176: BENF_ADDR
  177: ON_BRD_DT
  178: AGNT_CRR